### ISSUE TITLE
Implement atomic string

### ISSUE THREAD

**Issue by cristaloleg** [cristalhq/atomix#1]
Can be done as a simple wrapper over https://godoc.org/sync/atomic#Value

Expected api: `Load`, `Store`, `CAS`
And 1 test function for all this methods.

**Comment by absagar** [comment]
@cristaloleg the `atomic.Value` type doesn't support the `CAS` api. So, we either do not implement CAS for atomic string or use locks/mutexes for synchronising access to all the operations which I dont think is a good idea to implement in a wrapper. Thoughts ?

I can create a pull request for atomic strings with `Load` and `Store`.

**Comment by cristaloleg** [comment]
Hm, ok, `Load` and `Store` will be enough, thank you.
